version: "3.4"

services:
  chatbot:
    build: ./docker/chatbot
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - INTELX_API_KEY=${INTELX_API_KEY}
    volumes: 
      - ./data:/data
      - ./samples:/samples
    restart: always

  frontend:
    build: docker/frontend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 3000:3000
  uml:
    image: plantuml/plantuml-server:tomcat
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml

