version: "3.4"

services:
  chatbot:
    build: ./docker/chatbot
    environment:
      - DB_DIR=${DB_DIR}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes: 
      - ./data:/data
      - ./samples:/samples
    restart: always

  frontend:
    build: docker/frontend
    ports:
      - 3000:3000
  uml:
    image: plantuml/plantuml-server:tomcat
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml

