version: "3.4"

services:
  chatbot:
    build: ./docker/chatbot
    ports:
      - 9000:9000
    environment:
      - DB_FILE=${DB_FILE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes: 
      - ./data:/data
    restart: always
